# Generated by Django 3.1.5 on 2021-07-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creator',
            new_name='author',
        ),
    ]
