# Generated by Django 3.1.5 on 2021-07-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_auto_20210730_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='videoes', to='creators.module'),
            preserve_default=False,
        ),
    ]
