# Generated by Django 3.1.5 on 2021-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='learning_points',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
