# Generated by Django 3.1.5 on 2021-08-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_auto_20210804_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
