# Generated by Django 3.1.5 on 2021-08-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_auto_20210810_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sales',
            field=models.BigIntegerField(default=0),
        ),
    ]
